nelmio_api_doc:
  documentation:
    info:
      title: Rest CRUD API
      description: This is project for test
      version: 1.0.0
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: []
  areas:
    path_patterns:
      - ^/api/(?!doc)