version: "3.8"

services:
  mysql_db:
    image: mysql:8.0
    command: mysqld --sql_mode="" --sort_buffer_size=512K --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./docker/database:/var/lib/mysql:cached
  nginx:
    image: nginx:latest
    volumes:
      - ./public/:/usr/src/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ./:/usr/src/app:cached
      - ./docker/composer/:/.composer
      - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini
    user: ${LOCAL_USER}

networks:
  default:
    name: rest_crud