parameters:
    nbu_api.base_url: '%env(NBU_API_BASE_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\ExceptionHandler:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\EventListener\TimestampableListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preRemove }

    App\Service\SalaryCalculate\Interface\SalaryCalculatorInterface $averageSalaryCalculator:
        alias: App\Service\SalaryCalculate\AverageSalaryCalculator
    App\Service\SalaryCalculate\Interface\SalaryCalculatorInterface $salaryIncreaseCalculator:
        alias: App\Service\SalaryCalculate\SalaryIncreaseCalculator

    App\ApiClient\NbuApiClient:
        arguments:
            $baseUrl: '%nbu_api.base_url%'