name: Deploy to Server

on:
  push:
    branches:
      - master  # Или ваша основная ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Check Variables
        run: |
          echo "DEPLOY_USER is: $DEPLOY_USER"
          echo "SERVER_IP is: $SERVER_IP"
          echo "DEPLOY_PATH is: $DEPLOY_PATH"
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER || 'deployer' }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH || '/var/www/html' }}

      - name: Deploy to Server
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER || 'deployer' }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH || '/var/www/html' }}
        run: |
          ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$SERVER_IP" "
            cd $DEPLOY_PATH || exit;
            if [ ! -d .git ]; then
              git clone git@github.com:IgorPetrovi4/nelmioCrud.git $DEPLOY_PATH;
            else
              git pull origin master;
            fi
            composer install --no-interaction --prefer-dist --optimize-autoloader;
            php bin/console doctrine:migrations:migrate --no-interaction;
            php bin/console cache:clear --env=prod --no-debug;
          "